//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TicTacToe.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }

        public static string LanguageOptions {
            get {
                return ResourceManager.GetString("LanguageOptions", resourceCulture);
            }
        }

        public static string GridOptions {
            get {
                return ResourceManager.GetString("GridOptions", resourceCulture);
            }
        }

        public static string AskForMoveX {
            get {
                return ResourceManager.GetString("AskForMoveX", resourceCulture);
            }
        }

        public static string AskForMoveO {
            get {
                return ResourceManager.GetString("AskForMoveO", resourceCulture);
            }
        }

        public static string InvalidMove {
            get {
                return ResourceManager.GetString("InvalidMove", resourceCulture);
            }
        }

        public static string CongratulateX {
            get {
                return ResourceManager.GetString("CongratulateX", resourceCulture);
            }
        }

        public static string CongratulateO {
            get {
                return ResourceManager.GetString("CongratulateO", resourceCulture);
            }
        }

        public static string TieGame {
            get {
                return ResourceManager.GetString("TieGame", resourceCulture);
            }
        }
    }
}
